### ISSUE TITLE
Doesn't start due to wrong python directory (python 3.7 on linux)

### ISSUE THREAD

**Issue by niermann** [nion-software/nionswift-tool#3]
nionswift and nionswift-tool installed from PyPI (0.4.10, according to installation instruction for 0.15.6) into a virtual environment.

Executing nionswift does not start up the application, but exits with message (... being the correct path of the venv) 

> Using Python environment: ...
> Unable to find Python.

Using most recent nionswift-tool from Github (0.4.10, commit 72c83cc014a796950e6183831f290c7a5294531f) and fixing path in launcher/PythonSupport.cpp ("m" added in directory, line 269)
`   file_paths.append(home_dir.absoluteFilePath("lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.so"));
`   
fixes the issue and the nionswift application starts as expected.

On the good side: the new python home handling in 0.4.10 works in this setup (opposed to 0.4.9).

Environment:

    Ubuntu 18.04 with Python 3.7.9 from ubuntu-toolchain-r PPA.
    Nionswift 0.15.6 installed from PyPI into Python 3.7 virtual environment with upgraded pip

**Comment by cmeyer** [comment]
Is it easy for you to test either Python 3.8 or Python 3.9? I'm guessing they work OK since Python [dropped the "m" suffix](https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes) from their libraries, which meant "using pymalloc".

But overall, this launch issue is curious... the CI has tests for launching under Ubuntu 18 with Python 3.7 and it should fail too. I'm wondering why it doesn't.

Here is the [Ubuntu 18 / Python 3.7 CI build](https://github.com/nion-software/nionswift-tool/runs/2328268634), with the "ACK" at the end of the section "Test system Python installed with official build with virtual environment" representing the successful launch of the tool.

How has Python been installed on your system? Are you installing Swift in a virtual environment?

I'll also try this on my fresh Ubuntu 18 today and see if I can reproduce it.

**Comment by cmeyer** [comment]
For completeness, here are the commands for running the test "system python" test:

https://github.com/nion-software/nionui-tool/blob/master/.github/workflows/build.yml#L223-L239

**Comment by niermann** [comment]
I can confirm it works out of the box with python3.8.

While I originally tested it with the python3.7 package from the ubuntu-toolchain-r PPA, I now retested it with the python package from ubuntu's bionic-updates repository, which reproduces the same issue. Swift is installed into a (fresh) virtual environment.

We seem to use different python packages. The packages I used are installed into /usr/lib/python3.7 while the python package used in the CI tests are installed into /opt/hostedtoolcache/Python/3.7.10/x64/lib... 

It seems to boil down to the question what python package one uses (or supports). I assume the one in /opt/ comes from conda? Since the installation instructions mention it is possible to install swift from PyPI, I assumed Ubuntu's native python installation would also work.

I looked into the CI logs for Ubuntu 20.04/Python3.8: there also a python installation in /opt is used. Ubuntu 20.04 has Python 3.8 installed by default (in /usr/lib), opposed to Ubuntu 18.04 which ships with 3.6. So in principle there is no need to install conda for Ubuntu 20.04/Python3.8. (Obviously the whole 3.7 "m" thing isn't an issue there anymore at all)

**Comment by niermann** [comment]
Sorry, I didn't want to close the issue, just slipped on the button accidentally...

Looking at the commands for the system python test... it seems that the default system's python interpreter has been changed. If I run those commands on an (basically fresh) Ubuntu 18.04 the default system's interpreter called by the "python" command is even 2.7 (you might change this probably by some update-alternatives calls).

**Comment by cmeyer** [comment]
Linux is not my regular OS - I use macOS for most development; and Windows gets heavily tested on the microscopes. So my question is whether I should extend the CI tests to include the ubuntu-toolchain-r PPA and/or the bionic-updates? It sounds like those would be good additions to the CI. Are those the "normal" way that someone would update Python on their Ubuntu machine?

Also, we generally support up to two previous Python versions. When Python 3.10 is released later this year, we'll drop support for Python 3.7 - so this issue will become moot. However, I think running tests with other Python installations would be useful to avoid similar type bugs in the future with 3.8+.

**Comment by cmeyer** [comment]
> Sorry, I didn't want to close the issue, just slipped on the button accidentally...
> 
> Looking at the commands for the system python test... it seems that the default system's python interpreter has been changed. If I run those commands on an (basically fresh) Ubuntu 18.04 the default system's interpreter called by the "python" command is even 2.7 (you might change this probably by some update-alternatives calls).

Yes, I think the CI environments have a bunch of updates already. I've found it difficult to get "fresh" installations without a using whole different level of CI knowledge. I decided to start with the easy stuff (pre-made CI images).

**Comment by niermann** [comment]
Even with 10+ experience as user/admin/developer on ubuntu/debian systems I not really know what the "normal" way is. If a package exists its in the official repositories (incl. updates or even in the backports repository), I would always opt for that. For me installing from other PPAs feels already less "official", unless it is the official PPA from the maintainer of a software package. Even compiling a (non-system) python interpreter version on my own, seems a natural way for installing it for me. 

I agree that given your support cycle python 3.7 is of no issue anymore in the next future. In my view, at least the interpreters in the "official" ubuntu repositories seems worth to include in CI tests. I personally never saw a reason to reach for conda distributions on linux (on Windows its a different thing).

I have no experience with the CI tools myself yet. Even if I clearly see their benefit, they seem to come with a steep learning curve... However, "easy stuff" is much better than nothing. And it seems you already have an impressive CI toolchain up.

**Comment by cmeyer** [comment]
I did make the change so that it searches in the 37m subfolder.  https://github.com/nion-software/nionui-tool/commit/cc72239b75f6d3b54a39a89404e96c35d56fbb1f The change is untested on CI and won't be included until I release the 04.11 tools, probably next month, but maybe sooner - I'm working on a Linux Appimage version that is drag and drop and that might require an associated tool release.

The workaround for now is to use Python 3.8 or Python 3.9 (recommended) when installing from PyPI on Linux.
