### ISSUE TITLE
Qt 6.6 breaks compatibility with Ubuntu 22.04

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-tool#9]
When using nionswift-tool > 0.4.20 on Ubuntu 22.04, Swift does not start anymore with the following error message:

```
/home/andi/miniconda3/envs/developer/bin/NionSwiftLauncher/NionSwiftLauncher: symbol lookup error: /home/andi/miniconda3/envs/developer/bin/NionSwiftLauncher/NionSwiftLauncher: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
```
As far as I can tell the problem is that for Ubuntu 22.04, the highest available version of Qt6 is 6.2.4. Apparently that is not compatible with Qt 6.6 anymore. This seems to be a known problem: https://archlinux.org/todo/qt-662-abi-break/

**Comment by cmeyer** [comment]
~~What channel did you use to install `nionswift-tool` are you using? Can you try the version from the `nion` channel? The one in `conda-forge` has known issues.~~

I tried this and I think we're going to have to package Qt like we do it for the installer.

**Comment by cmeyer** [comment]
@Brow71189 Can this be closed now?

**Comment by Brow71189** [comment]
As far as I can tell, the latest nionui-tool version fixes this, so let's close it.
